services:
    laravel.gateway:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            GRUPOS_SERVICE_URL: 'http://grupos-service:3001'
            MATERIAS_SERVICE_URL: 'http://materias-service:3000'
            USUARIOS_SERVICE_URL: 'http://perfil-service:3002'
            ACADEMIA_SERVICE_URL: 'http://academia-service:3003'
            INSCRIPCIONES_SERVICE_URL: 'http://laravel.inscripciones'
        volumes:
            - '.:/var/www/html'
        depends_on: {  }
networks:
    default:
        external: true
        name: microservicios-topicos
